### ISSUE TITLE
Can we use Named parameters in SQL queries with amphp\mysql package?

### ISSUE THREAD

**Issue by raghuveer** [amphp/mysql#106]
While I am able to use question marks in prepared statements, I am getting error when I try to use named parameters when making insert query

my code using question marks (worked):

```
$sql = "INSERT INTO site_members (lastname, firstname) VALUES (?, ?)";
$statement = yield $pool->prepare($sql);
$result = yield $statement->execute(['Doe', 'John']);
$id = $result->getLastInsertId();
echo "id: " . $id . "\n";
```

code with named parameters:

```
$array = array(':lastname' => 'Doe', ':firstname' => 'John');
				
$sql = "INSERT INTO site_members (lastname, firstname) VALUES (:lastname, :firstname)";
$statement = yield $pool->prepare($sql);
$result = yield $statement->execute($array);
$id = $result->getLastInsertId();
echo "id: " . $id . "\n";
```

when I try using named parameters, as shared in the above, I get the following error:

```
PHP Fatal error:  Uncaught Error: Named parameter 'lastname' missing for executing prepared statement in /home/user/public_html/vendor/amphp/mysql/src/ConnectionStatement.php:124
Stack trace:
#0 /home/user/public_html/vendor/amphp/sql-common/src/PooledS                                                                                      tatement.php(64): Amp\Mysql\ConnectionStatement->execute()
#1 [internal function]: Amp\Sql\Common\PooledStatement->Amp\Sql\Common\{closure}                                                                                                             ()
#2 /home/user/public_html/vendor/amphp/amp/lib/Coroutine.php(                                                                                                             67): Generator->current()
#3 /home/user/public_html/vendor/amphp/amp/lib/functions.php(                                                                                                             96): Amp\Coroutine->__construct()
#4 /home/user/public_html/vendor/amphp/sql-common/src/PooledS                                                                                                             tatement.php(72): Amp\call()
#5 /home/user/public_html/vendor/amphp/sql-common/src/Stateme                                                                                                           ntPool.php(105): Amp\Sql\Common\PooledStatement->execute()
#6 [internal function]: Amp\Sql\Common\StatementPool->Amp\Sql\Common\{closure}()
#7 /home/user/public_html/vendor/amphp in /home/user/public_html/vendor/amphp/mysql/src/ConnectionStatement.php on line 12                                                                                                             4
```

**Comment by kelunik** [comment]
The issue you're facing appears, because you're prefixing your array of parameters with a colon, so use `$array = array('lastname' => 'Doe', 'firstname' => 'John');` instead of `$array = array(':lastname' => 'Doe', ':firstname' => 'John');`.

**Comment by raghuveer** [comment]
Dear Kelunik

Thanks for your quick response, I did try the following:

a) removed colon before named parameters, when insert query happened but values are not inserted

$array = array('firstname' => 'Johnaqwzx', 'lastname' => 'Doeaqwzx');
				
$sql = "INSERT INTO site_members (firstname, lastname) VALUES (firstname, lastname)";
$statement = yield $pool->prepare($sql);
$result = yield $statement->execute($array);
$id = $result->getLastInsertId();
echo "id: " . $id . "\n";

Note: auto-increment for primary key of the database table is ENABLED in this scenario.

b) removed auto-increment for primary key of the database table, when I am getting following error, irrespective of whether I give a number or a numeric string or other for the column with primary key

primary key column: id

query:

$array = array('id' => '21234', 'firstname' => 'Johnaqwzxcvbsd', 'lastname' => 'Doeaqwzxcvbsd');
				
$sql = "INSERT INTO site_members (id, firstname, lastname) VALUES (id, firstname, lastname)";
$statement = yield $pool->prepare($sql);
$result = yield $statement->execute($array);
$id = $result->getLastInsertId();
echo "id: " . $id . "\n";

error message: 
PHP Fatal error:  Uncaught Amp\Sql\QueryError: MySQL error (1062): #23000 Duplicate entry '0' for key 'PRIMARY'
Current query was INSERT INTO site_members (id, firstname, lastname) VALUES (id, firstname, lastname) in /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php:707
Stack trace:
#0 /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php(1444): Amp\Mysql\Internal\Processor->handleError()
#1 /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php(294): Amp\Mysql\Internal\Processor->parsePayload()
#2 /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php(261): Amp\Mysql\Internal\Processor->processData()
#3 [internal function]: Amp\Mysql\Internal\Processor->read()
#4 /home/user/public_html/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#5 /home/user/public_html/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\C in /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php on line 707

Thank you for your help
