### ISSUE TITLE
Can we have lastInsertId returned in a different method when UUID is used as Primary Key?

### ISSUE THREAD

**Issue by raghuveer** [amphp/mysql#107]
Request: Wish to receive lastInsertId in a separate method, after being typecasted to string, to be useful when UUID is generated externally and submitted as Primary Key in the Insert Query.

Can an additional method be added in the CommandResult class for this purpose?

https://github.com/amphp/mysql/blob/master/src/CommandResult.php

is it ok, to make a pull request for this change?

thank you

**Comment by kelunik** [comment]
If you generate the UUID externally, it should already be available in the client code that issues the insert query, no?

**Comment by raghuveer** [comment]
you are right @kelunik 

thing is, we are creating a small wrapper class on top of amphp\mysql, wherein, we are providing last insert id, in the method in following two scenarios,

a) with db tables that has auto increment enabled
b) with db tables that has auto increment disabled and UUID or other unique strings are expected to act as primary key

since, in CommandResult class, the getInsertId method has been typecasted to integer, thinking on how we can have two insert methods for above mentioned two scenarios, while using methods available in amphp\mysql class.

made the request in this context, to see if a method can be added with a different name, to provide getInsertId response as a string, so I can adopt those two methods as mentioned in the above.

thank you

**Comment by kelunik** [comment]
@raghuveer Seems like you'll want to wrap the `CommandResult` in a custom object then, no?

**Comment by raghuveer** [comment]
it will be really helpful if you can please elaborate @kelunik 
being a procedural php guy, I do write classes only when needed, can you please share an example

thank you

**Comment by trowski** [comment]
Based on the other issues, it looks like you found a solution to this problem. Feel free to reopen this issue or create a new one if you need further assistance.
