### ISSUE TITLE
Values not saved when named parameters are used in SQL insert queries with amphp\mysql package

### ISSUE THREAD

**Issue by raghuveer** [amphp/mysql#109]
The issue you're facing appears, because you're prefixing your array of parameters with a colon, so use `$array = array('lastname' => 'Doe', 'firstname' => 'John');` instead of `$array = array(':lastname' => 'Doe', ':firstname' => 'John');`.

_Originally posted by @kelunik in https://github.com/amphp/mysql/issues/106#issuecomment-763585244_

Dear Kelunik

Thanks for your quick response, I did try the following:

a) removed colon before named parameters, when insert query happened but values are not inserted

$array = array('firstname' => 'Johnaqwzx', 'lastname' => 'Doeaqwzx');

$sql = "INSERT INTO site_members (firstname, lastname) VALUES (firstname, lastname)";
$statement = yield $pool->prepare($sql);
$result = yield $statement->execute($array);
$id = $result->getLastInsertId();
echo "id: " . $id . "\n";

Note: auto-increment for primary key of the database table is ENABLED in this scenario.

b) removed auto-increment for primary key of the database table, when I am getting error, irrespective of whether I give a number or a numeric string or other for the column with primary key

primary key column: id

query:

$array = array('id' => '21234', 'firstname' => 'Johnaqwzxcvbsd', 'lastname' => 'Doeaqwzxcvbsd');

$sql = "INSERT INTO site_members (id, firstname, lastname) VALUES (id, firstname, lastname)";
$statement = yield $pool->prepare($sql);
$result = yield $statement->execute($array);
$id = $result->getLastInsertId();
echo "id: " . $id . "\n";

error message:
PHP Fatal error: Uncaught Amp\Sql\QueryError: MySQL error (1062): #23000 Duplicate entry '0' for key 'PRIMARY'
Current query was INSERT INTO site_members (id, firstname, lastname) VALUES (id, firstname, lastname) in /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php:707
Stack trace:
#0 /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php(1444): Amp\Mysql\Internal\Processor->handleError()
#1 /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php(294): Amp\Mysql\Internal\Processor->parsePayload()
#2 /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php(261): Amp\Mysql\Internal\Processor->processData()
#3 [internal function]: Amp\Mysql\Internal\Processor->read()
#4 /home/user/public_html/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#5 /home/user/public_html/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\C in /home/user/public_html/vendor/amphp/mysql/src/Internal/Processor.php on line 707

Thank you for your help

**Comment by kelunik** [comment]
You should only remove the colon in the array, not in the query itself.

**Comment by raghuveer** [comment]
Thanks a lot @kelunik it worked.

to my surprise, my trials are in the scope of PDO based named parameters, I am used to over years, and now, it worked, after removing colon for named parameter references in values array while still retaining the named parameter references with colon in the sql insert query, irrespective of whether auto-increment is enabled/disabled on the primary key column of the database table.

**Comment by kelunik** [comment]
@raghuveer Glad to hear it worked. :)
