### ISSUE TITLE
about wrapping CommandResult

### ISSUE THREAD

**Issue by raghuveer** [amphp/mysql#110]
@raghuveer Seems like you'll want to wrap the `CommandResult` in a custom object then, no?

_Originally posted by @kelunik in https://github.com/amphp/mysql/issues/107#issuecomment-763658254_

it will be really helpful if you can please elaborate @kelunik
being a procedural php guy, I do write classes only when needed, can you please share an example

thank you

**Comment by kelunik** [comment]
@raghuveer Please don't open a new issue every time, but comment on the existing one.
