### ISSUE TITLE
multi query with prepared statement

### ISSUE THREAD

**Issue by ori1989** [amphp/mysql#112]
The code:

```
  ...

  $sql = 'SELECT * from temp1 WHERE id = :id1; 
      SELECT * from temp2 WHERE id = :id2';

  $data = ['id1' => 1, 'id2' => 1];

  $stmt = yield $db->prepare($sql);
  $result = yield $stmt->execute($data);

  ...
```
I try to run this code, and I get error.

**Comment by enumag** [comment]
What error?

**Comment by ori1989** [comment]
Fatal error: Uncaught Amp\Sql\QueryError: MySQL error (1064): #42000 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT * from temp2 WHERE id = ?' at line 2 Current query was SELECT * from temp1 WHERE id = :id1; SELECT * from temp2 WHERE id = :id2;
...

**Comment by fshahzad** [comment]
You can try the 'Union' or 'Union All' between two or more queries.

**Comment by trowski** [comment]
This is now supported in the v3 branch compatible with Amp v3 + PHP 8.1 + fibers.
