### ISSUE TITLE
Prepared Statements don't work with DATETIME columns

### ISSUE THREAD

**Issue by bennnjamin** [amphp/mysql#119]
UPDATE: I have done some more testing and noticed that it works when I specify column names. 

I have a very simple example that I'm testing v3 on with my own development database. The following code runs with no errors, but the result is empty since nothing is printed. If I use the ```db->query(...)``` function and don't use prepared statements, but instead pass values directly in the sql string it works. Any ideas how to troubleshoot this or any guidance on prepared statements would be greatly appreicated.

```php
$email = "mytestemail";

$db = new MysqlConnectionPool(MysqlConfig::fromAuthority($host, $user, $pass, $database));

$stmt = $db->prepare("SELECT * FROM users WHERE email = ?");


$result = $stmt->execute([$email]);
foreach ($result as $row) {
    print_r($row);
}

$result2 = $db->execute("SELECT * FROM users WHERE email = ?", [$email]);
foreach ($result2 as $row) {
    print_r($row);
}

**Comment by bennnjamin** [comment]
Turns out that any columns of type ```DATETIME, TIME, TIMESTAMP``` are not decoded properly, causing this issue.

**Comment by trowski** [comment]
Fixed via https://github.com/amphp/mysql/commit/3a2c329e391df63fb282a282d5eb792685d66e46.
