### ISSUE TITLE
Incorrect handling of fractional seconds in Datetime, and Timestamp columns

### ISSUE THREAD

**Issue by bennnjamin** [amphp/mysql#125]
I came across this when integrating with some PHP code that expects the SQL column to return a Datetime like ```yyyy-MM-dd HH:mm:ss``` and I was instead receiving the fractional seconds as all 0's instead.

The bug starts in this line https://github.com/amphp/mysql/blob/8482a6875fe57bf6df3784b8e60b2bf375dd1957/src/MysqlDataType.php#L145

Even if the database does not return fractional seconds, it is still initialized to 0 and padded at the end of the string here:
https://github.com/amphp/mysql/blob/8482a6875fe57bf6df3784b8e60b2bf375dd1957/src/MysqlDataType.php#L173
However if you read their description of this feature here https://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html, there should be no fractional seconds unless it's defined on the column. 

I believe it is just a matter of ensuring that fractional seconds are not appended to the string unless this case is satisfied: https://github.com/amphp/mysql/blob/8482a6875fe57bf6df3784b8e60b2bf375dd1957/src/MysqlDataType.php#L147

Right now, it's not that hard to workaround but I think it's something that will surprise a lot of users that are not expecting fractional seconds in their string handling of these column types.

I haven't tested with "Date" or "Time" column types but those may be affected as well.

**Comment by layerkugou** [comment]
good  thankyou

**Comment by bennnjamin** [comment]
Fixed in v3.0.0-beta.4

**Comment by trowski** [comment]
Yes, sorry, I apparently had noticed this myself when refactoring how data types were handled and then tagged the beta without closing this issue. Thank you for noticing and closing!
