### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by HubbGit** [amphp/mysql#127]
Why composer require amphp/mysql  requires previous version of amphp/amp?
How can I install latest amphp/mysql  with latest amphp/amp?

[master@fedora lib.test]$ composer require amphp/mysql
./composer.json has been updated
Running composer update amphp/mysql
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - amphp/mysql[v0.1.0, ..., v0.1.6] require amphp/amp ^1 -> found amphp/amp[v1.0.0, ..., v1.2.2] but it conflicts with your root composer.json require (^3.0).
    - amphp/mysql[v0.2.0, ..., v0.3.1, v2.0.0, ..., v2.1.3] require amphp/amp ^2 -> found amphp/amp[v2.0.0, ..., v2.6.2] but it conflicts with your root composer.json require (^3.0).
    - amphp/mysql[v1.0.0, ..., v1.2.1] require php ^7.0 -> your php version (8.2.5) does not satisfy that requirement.
    - Root composer.json requires amphp/mysql * -> satisfiable by amphp/mysql[v0.1.0, ..., v0.3.1, v1.0.0, v1.1.0, v1.2.0, v1.2.1, v2.0.0, ..., v2.1.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require amphp/mysql:*" to figure out if any version is installable, or "composer require amphp/mysql:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by kelunik** [comment]
There's no stable version of amphp/mysql, yet, that supports Amp v3. You can however use the lastest beta version if you want to use Amp v3.

**Comment by HubbGit** [comment]
composer require amphp/mysql:@dev
./composer.json has been updated
Running composer update amphp/mysql
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Segmentation fault (core dumped)

**Comment by kelunik** [comment]
That's some issue in PHP itself then. Please upgrade to the latest version before reporting an issue to https://github.com/php/php-src.

**Comment by danog** [comment]
I'd recommend uninstalling the zip extension, I've been getting this issue randomly too when using composer with the zip extension enabled

**Comment by parsibox** [comment]
require amphp/sql v2.0.0-beta.6 amphp/sql-common v2.0.0-beta.10 amphp/amp amphp/mysql 3.x-dev
