### ISSUE TITLE
Change connection string to URI

### ISSUE THREAD

**Issue by kelunik** [amphp/mysql#19]
I think it would be good to use URIs to configure connections, e.g. `mysql://user:password@host:port/database?timeout=abc`. URIs provide everything we need: User + password on host / port, a database name as path and options via URL parameters.

**Comment by DaveRandom** [comment]
worth noting that pgsql (libpq itself) already does this

**Comment by kelunik** [comment]
Redis does this as well, I think, at least I planned it.
