### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by kelunik** [amphp/mysql#24]
There should be examples for transactions and probably a dedicated API.

**Comment by shtse8** [comment]
Any updates?

**Comment by kelunik** [comment]
Not yet, feel free to make an API suggestion.

**Comment by shtse8** [comment]
$connection = $mysqlPool->getConnection();
- Get a free connection from the pool. the marking the connection is busy.

$connection->query();
- query using the connection.

$connection->release();
- Release back the connection to the connection pool.

$connection->beginTransaction();
- query `START TRANSACTION`

$connection->commit();
- query `COMMIT`

$connection->rollback();
- query `ROLLBACK`

$connection = $mysqlPool->beginTransaction();
- auto calling `$mysqlPool->getConnection()`, then `$connection->beginTransaction()`, return a ready-to-use connection for transaction.

**Comment by kelunik** [comment]
@trowski This has been implemented, no?

**Comment by bwoebi** [comment]
@kelunik Yes, it was. See e.g. https://github.com/amphp/mysql/blob/master/examples/6-transaction.php
