### ISSUE TITLE
Check Stmt::bind() types

### ISSUE THREAD

**Issue by torinaki** [amphp/mysql#39]
If you will run following code:
```
$stmt->bind('id', [1,2,3,4,5]);
```
you will get following error:
```
Notice: Array to string conversion
```

As quick solution you can use Doctrine helper function to convert params to flat array:
```
list($sql, $params, $paramsType) = SQLParserUtils::expandListParameters($query->getSQL(), $query->getParameters(), $query->getParameterTypes());
```

**Comment by bwoebi** [comment]
Doctrine is doing its own binding, emulating prepared statements itself, allowing this.

However, this library uses the native binding of the mysql protocol. If you send `SELECT * FROM table WHERE id IN (?)`, mysql expects exactly one value to be bound there. There's no way around that inherent limitation of the mysql protocol, except by emulating binding yourself. It will never be possible to write the following:
```php
$stmt = yield $conn->prepare("SELECT * FROM table WHERE id IN (?)");
$result = yield $stmt->execute([$ids]);
```

It *may* make sense to allow reused placeholder keys being filled with array items. Thus, we could make this work:
```php
$stmt = yield $conn->prepare("SELECT * FROM table WHERE id IN (".substr(str_repeat(", :id", count($ids)), 2).")");
$result = yield $stmt->execute(["id" => $ids]);
```

Though, what already works today is mixing named and unnamed parameters (unlike e.g. in PDO):
```php
$stmt = yield $conn->prepare("SELECT * FROM table WHERE secondary_qualifier = :secondary AND id IN (".substr(str_repeat(", ?", count($ids)), 2).")");
$result = yield $stmt->execute(["secondary" => "some value"] + $ids);
```

**Comment by torinaki** [comment]
@bwoebi at least invalid argument handling must be implemented instead of throwing notice:
```
Notice: Array to string conversion
```

**Comment by kelunik** [comment]
@torinaki Feel free to submit a PR checking that the value is scalar.

**Comment by kelunik** [comment]
I guess we could add `Amp\Mysql\paramList(array)` returning `substr(str_repeat(", ?", count($ids)), 2)`.
