### ISSUE TITLE
Warning that lead to process hung

### ISSUE THREAD

**Issue by torinaki** [amphp/mysql#40]
After following warning process hung:
```
Warning: unpack(): Type V: not enough input, need 4, have 1 in ./vendor/amphp/mysql/lib/DataTypes.php on line 293
```
Currenlty I'm not able to find steps to reproduce. It appears randomly.

**Comment by bwoebi** [comment]
Depending on where in the code this originates from, it indeed may lead to every query being stalled permanently as well as the related Promises obviously then.

Would be quite important to know when this happens; to start a backtrace for the context would help a lot. (e.g. an error handler calling `print new \Exception;`)
Also, try setting `define("MYSQL_DEBUG", true);`. This will log the whole raw protocol I/O stream to stderr.

Thanks :-)

**Comment by torinaki** [comment]
@bwoebi it finally have stopped with uncatched exception:
```
  Loop stopped without resolving the promise

Exception trace:
 () at /home/sites/dmitry.balabka/src/internal-search/vendor/amphp/amp/lib/functions.php:164
 Amp\Promise\wait()
... [remaining stacktrace related to application methods calls] ...
````

I will try to get MySQL protocol dump

**Comment by torinaki** [comment]
@bwoebi the last message from MySQL log. I have obfuscated the data
```
in: 7b 0 0 6d 0 0 0 38 50 0 0 8e 6 0 0 64 c 0 0 22 41 61 61 61 61 61 61 61 61 61 61 20 41 42 43 2D 31 20 42 62 62 62 62 62 20 43 63 63 63 63 63 63 63 63 1d 61 61 61 61 61 61 61 61 61 61 61 2D 61 62 63 2D 31 2D 62 62 62 62 62 62 2D 63 63 63 63 22 41 61 61 61 61 61 61 61 61 61 61 20 41 42 43 2D 31 20 42 62 62 62 62 62 3f 0 78 9c d5 5b 79 90 14 d5 19 ff 14 5c 34 12 92 a2 
len: 123 string(123) "...8P..�...d..."Aaaaaaaaaaa ABC-1 Bbbbbb Ccccccccc.aaaaaaaaaaa-abc-1-bbbbbb-cccc"Aaaaaaaaaaa ABC-1 Bbbbbb?.x��[y�.�.�.\4.��"
```

**Comment by bwoebi** [comment]
I _suppose_ this is a binary result set row packet. I do not have any information about the columns, so this is useless for me.

I need to know what format the columns it tries to parse have, otherwise this is just binary gibberish. (basically: give me more log data. If it contains sensitive data, feel free to mail me to bobwei9@hotmail.com instead.)

Also: I meant a backtrace from within the Warning.

**Comment by bwoebi** [comment]
@torinaki ping - do you have any further information for me here?

**Comment by torinaki** [comment]
@bwoebi here is trace:
```
Warning: unpack(): Type V: not enough input, need 4, have 1 in ./vendor/amphp/mysql/lib/DataTypes.php on line 293
Exception in ./vendor/amphp/mysql/lib/DataTypes.php:296
Stack trace:
#0 ./vendor/amphp/mysql/lib/Processor.php(995): Amp\Mysql\DataTypes::decode_unsigned24('')
#1 [internal function]: Amp\Mysql\Processor->parseCompression()
#2 ./vendor/amphp/mysql/lib/Processor.php(950): Generator->send('V\x0F\x00\x03\x00@\x00x\x9C\xAD[ip\x1C\xC5...')
#3 ./vendor/amphp/amp/lib/Loop/NativeDriver.php(162): Amp\Mysql\Processor->onRead('t', Resource id #609, NULL)
#4 ./vendor/amphp/amp/lib/Loop/NativeDriver.php(68): Amp\Loop\NativeDriver->selectStreams(Array, Array, 3.124)
#5 ./vendor/amphp/amp/lib/Loop/Driver.php(130): Amp\Loop\NativeDriver->dispatch(true)
#6 ./vendor/amphp/amp/lib/Loop/Driver.php(70): Amp\Loop\Driver->tick()
#7 ./vendor/amphp/amp/lib/Loop.php(53): Amp\Loop\Driver->run()
#8 ./vendor/amphp/amp/lib/functions.php(158): Amp\Loop::run(Object(Closure))
... [remaining stacktrace related to application methods calls] ...
```
and I have complete mysql log.
Library version
```
            "name": "amphp/mysql",
            "version": "v0.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/amphp/mysql.git",
                "reference": "6ae0e7696ce6cdc0f535ee7a629887d376482921"
            },
```

**Comment by bwoebi** [comment]
Ah that's it :-) Given the stacktrace it now was really obvious what went wrong, thanks!

**Comment by torinaki** [comment]
@bwoebi seems everything fine. I did multiple trials with latest master and didn't notice any problems.

**Comment by kelunik** [comment]
@bwoebi Could you tag a new bugfix then?

**Comment by bwoebi** [comment]
Tagged v0.2.2.
