### ISSUE TITLE
Not possible to set limit on Pool.

### ISSUE THREAD

**Issue by NicklasWallgren** [amphp/mysql#43]
Connection::parseConnStr($connStr, $sslOptions) fails with " Undefined offset: 1"

Connection string
```
limit=2;host=<host>;user=<user>;pass=<pass>;db=<database>
```

**Comment by NicklasWallgren** [comment]
Sure.

There seem to be additional problems using the limit option. I would say that 50 % of the time the promises won't resolve and the script get stuck in the driver loop, while not seeing any activity in the processlist in MySQL.

**Comment by NicklasWallgren** [comment]
Alright, found the "real" cause behind the problem.

If a query results in a warning or such, then the queue will get stuck in the driver loop. 

```
Query OK, 0 rows affected, 2 warnings (0.00 sec)
```
```
Query OK, 5 rows affected, Duplicates: 0, 2 warnings (0.00 sec)
``

**Comment by NicklasWallgren** [comment]
Example

```
$pool = new Pool('limit=2;.....');

        $promises[] = $pool->query('INSERT INTO mysql.user (Host, User) VALUES("localhost", "root") ON DUPLICATE KEY UPDATE User = User', []);
        $promises[] = $pool->query('INSERT INTO mysql.user (Host, User) VALUES("localhost", "root") ON DUPLICATE KEY UPDATE User = User', []);
        $promises[] = $pool->query('INSERT INTO mysql.user (Host, User) VALUES("localhost", "root") ON DUPLICATE KEY UPDATE User = User', []);
        $promises[] = $pool->query('INSERT INTO mysql.user (Host, User) VALUES("localhost", "root") ON DUPLICATE KEY UPDATE User = User', []);
        $promises[] = $pool->query('INSERT INTO mysql.user (Host, User) VALUES("localhost", "root") ON DUPLICATE KEY UPDATE User = User', []);
        $promises[] = $pool->query('INSERT INTO mysql.user (Host, User) VALUES("localhost", "root") ON DUPLICATE KEY UPDATE User = User', []);
        $promises[] = $pool->query('INSERT INTO mysql.user (Host, User) VALUES("localhost", "root") ON DUPLICATE KEY UPDATE User = User', []);

        $i = 0;

        foreach ($promises as $promise) {
            \Amp\Promise\wait($promise);

            var_dump(++$i);
        }
```

**Comment by NicklasWallgren** [comment]
```

**Comment by bwoebi** [comment]
Okay, but it's not related to the warnings. I could reproduce the issue though. Looking into it.

**Comment by bwoebi** [comment]
Can you please verify whether 81195e21c3fe41092362fcee42c7612f64513b7f fixes your issue? Thanks :-)

I'm a bit stunned about that bug that it hasn't been discovered yet, but probably nobody bothered with connection limits before and 99% of the queries are handled via prepare() mechanism I guess, so that it just never happened to be an issue (as the Pool would just create new connections then and clean the old ones up after a while …).

**Comment by NicklasWallgren** [comment]
Yea, that solved the issue. Thanks :)

**Comment by NicklasWallgren** [comment]
Can you please tag this release?

**Comment by bwoebi** [comment]
I'll tag later - for some reason tests are failing now...

**Comment by bwoebi** [comment]
@NicklasWallgren tagged now :-)
