### ISSUE TITLE
Call to a member function isReady() on null

### ISSUE THREAD

**Issue by shtse8** [amphp/mysql#47]
```
 Uncaught Error: Call to a member function isReady() on null in /vendor/amphp/mysql/lib/ConnectionPool.php:136 
```

**Comment by shtse8** [comment]
https://github.com/amphp/mysql/blob/master/lib/ConnectionPool.php#L136
I have `var_dump($this->ready);`
Result:
```

array(3) {
--
  | [2]=>
  | &NULL
  | [3]=>
  | object(Amp\Mysql\Connection)#146 (1) {
  | ["processor":protected]=>
  | object(Amp\Mysql\Processor)#150 (32) {


```

**Comment by shtse8** [comment]
It seems `ConnectionPool.php` is full of bugs.

for `ready()` 
I have dumped 
`hash` = `000000003e3ef7ea0000000069d7cd7c`
`connectionMap`
```
array(2) {
--
  | ["000000003e3ef7300000000069d7cd7c"]=>
  | int(0)
  | ["000000003e3ef7df0000000069d7cd7c"]=>
  | int(1)
  | }


```

**Comment by shtse8** [comment]
https://github.com/amphp/mysql/pull/46
I don't know if this is a correct fix. Please review.

**Comment by trowski** [comment]
Looks like the related PR was merged some time ago and the library has since been significantly refactored. Thanks @shtse8!
