### ISSUE TITLE
ConnectionPool does not close idle connections

### ISSUE THREAD

**Issue by brstgt** [amphp/mysql#52]
There should be a mechanism like in \Amp\Socket\BasicSocketPool that closes idle connection after a defined amount of time.
Currently it is not possible to release idle connections gracefully. You can only dispense / replace the whole pool to get rid of idle connections which IMHO is not a viable solution.
In production peaks can created. E.g. by a slightly overloaded server. Not releasing idle connection can create a failure cascade e.g. when the server reaches max connections and starts dropping connection attempts.
This is unlikely to be an issue with a hand full of clients but if say 32 aerys workers are running on 30 machines each, each of them creating 10, 20, 50 connections to the same server AND not releasing them - this could become an issue.

**Comment by trowski** [comment]
I just replaced the pool implementation in v0.3.0, but this is still an issue in the new implementation. I'll look into adding a timer that closes connections after a period of time. Same in the postgres library.

**Comment by trowski** [comment]
@rdlowrey Yeah, that's the approach I was going to take. The pool implementation has a queue of idle connections where the most recently used goes at the end, so I should be able to just iterate from the front, removing connections as necessary. A busy pool would only need to examine a single connection.

**Comment by brstgt** [comment]
That's done, right?
