### ISSUE TITLE
Connection pool creates unnecessary connections

### ISSUE THREAD

**Issue by brstgt** [amphp/mysql#53]
ConnectionPool creates spare connections, even if I don't use a single one.

1. on constructor
2. In ::getReadyConnection()

If 0 connections are used, at least 1 is created
If 1 conneciton is used, 3 are created

If `addConnection` in c'tor and 
```        
if (count($this->ready) < 2) {
      $this->addConnection();
}
``` 
are removed, the number of connection seems to be correct.

**Comment by trowski** [comment]
I just tagged v0.3.0, can you test to see if there are issues with the new pool implementation?

**Comment by brstgt** [comment]
Looks much better in 0.3.x! Also thanks for refactoring! I was wondering why Pg/MySql interfaces were so different.

**Comment by bwoebi** [comment]
They were developed by different people at different times independently. Making the interfaces much more similar was a goal of 0.3
