### ISSUE TITLE
SegFault during unittest (maybe also normal code)

### ISSUE THREAD

**Issue by plankes-projects** [amphp/mysql#66]
When I am starting my unit test I get to this location which, if I step over it, produces a seg fault. Sadly I cannot share my unittest because I was not able to reproduce this in an easier environment. But I attached a screenshot of the stacktrace.

I think this is because I run into an infinity loop, visible in the screenshot.
The line of code I am breaking has jumped to Coroutine.php:93 on the previous 3 skips as visible in the screenshot.

I can reproduce this issue every time, so feel free to ask for more information.

amphp was installed with composer and has following versions:

amphp/amp                           dev-master c632e40 A non-blocking concurrency framework for PHP applications.
amphp/byte-stream                   v1.3.1             A stream abstraction to make working with non-blocking I/...
amphp/cache                         v1.2.0             A promise-aware caching API for Amp.
amphp/dns                           v0.9.12            Async DNS resolution for Amp.
amphp/file                          v0.3.1             Allows non-blocking access to the filesystem for Amp.
amphp/mysql                         dev-master f3e1f15 Asynchronous parallel Mysql client built on the Amp concu...
amphp/parallel                      v0.2.5             Parallel processing component for Amp.
amphp/parser                        v1.0.0             A generator parser to make streaming parsers simple.
amphp/process                       v0.3.2             Asynchronous process manager.
amphp/socket                        v0.10.8            Async socket connection / server tools for Amp.
amphp/sync                          v1.0.1             Mutex, Semaphore, and other synchronization tools for Amp.
amphp/uri                           v0.1.3             Uri Parser and Resolver.
amphp/windows-registry              v0.3.1             Windows Registry Reader.

![image](https://user-images.githubusercontent.com/10074105/38415375-993e73be-3991-11e8-9c93-850c761d7515.png)

**Comment by kelunik** [comment]
Which version of PHP are you running on? Does the segfault also happen if you disable xdebug?

**Comment by plankes-projects** [comment]
> php -v
PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:49) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans

Also fails if xdebug is disabled:
> php -v
PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:49) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies

**Comment by kelunik** [comment]
Could you please try with 7.1.16?

**Comment by plankes-projects** [comment]
Words with 7.1.16, thx! =D
