### ISSUE TITLE
Bug in timeout connector

### ISSUE THREAD

**Issue by prolic** [amphp/mysql#81]
The timeout configured is basically ignored. see vendor/amphp/socket/src/functions.php:70.

`$timeout = $socketContext->getConnectTimeout();`

so the timeout is fetched from socket context, the timeout from the timeout connector is more or less useless.

I found this while having default mysql timeout of 5 secs and got a timeout after 10 secs only.

**Comment by kelunik** [comment]
https://github.com/amphp/socket/blob/c3e4949921cc60de1eb127f963c53d9a7c68ba8a/src/functions.php#L135 needs a race with the cancellation converted to a promise basically.

**Comment by trowski** [comment]
The issue in `amphp/socket` where cancellation requests were not immediately honored was addressed in 
https://github.com/amphp/socket/commit/2cb9d0ef823cfd1de4cfbd0e680c58841367f727.
