### ISSUE TITLE
2.0 release date

### ISSUE THREAD

**Issue by elovin** [amphp/mysql#96]
The last RC for 2.0 is from October, whats the current estimated release date for 2.0 (Q2 2020 or Q3 2020)?

**Comment by trowski** [comment]
@elovin Have you used the 2.0 RC? I've been waiting for feedback on it before tagging, but haven't received much.

**Comment by elovin** [comment]
@trowski Im currently in the progress of replacing various reactphp based projects with amphp (ws server, ws client, process, file, mysql) so within the next few weeks I will be using the 2.0RC a lot, if any problems come up I will debug them and report it.  So that hopefully we can make a release in Q3 or Q4 2020  possible :)

**Comment by trowski** [comment]
For tagging 2.0, I'm more concerned about API feedback. If you discover any bugs later on, we can always tag a bug release. I don't really want to wait that long to tag 2.0, so unless you have any API suggestions, I'll probably tag 2.0 very soon. The API of this lib is very similar to `amphp/postgres`, which I personally use extensively, so I'm pretty comfortable that it doesn't have any major issues.

**Comment by elovin** [comment]
@trowski So far I do not have any API suggestions, I agree its probably best to just go ahead and tag 2.0.

**Comment by trowski** [comment]
2.0 tagged! \o/
